import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')

serve(async (req) => {
  const { record } = await req.json()

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Fetching Gargoyle <inquiry@fetchinggargoyle.com>',
      to: ['xander.k.hill@gmail.com'],
      subject: `New Contract Inquiry from ${record.name}`,
      html: `
        <h2>New Project Inquiry</h2>
        <p><strong>Client:</strong> ${record.name}</p>
        <p><strong>Email:</strong> ${record.email}</p>
        <p><strong>Message:</strong> ${record.message}</p>
        <br>
        <p><em>Generated by LLC Ops Automation</em></p>
      `,
    }),
  })

  return new Response(JSON.stringify({ message: "Email Sent" }), { 
    headers: { "Content-Type": "application/json" } 
  })
})